Updated documentation and tmux prefix

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+# Script to automatically install all required dependencies and symlink the
+# configurations.
+# Actual execution at the very end.
+#
+# If you pass "symlinks" as the only arg, only the symlinks will be linked.
+# Otherwise, everything will run.
+#
+# Keeps state in .state and sends output of most commands to output.log.
+
 common_packages=(
     fzf
     ripgrep
@@ -170,206 +179,208 @@ symlink_configs() {
         ln -snf "$SCRIPTPATH"/.config/sway "$HOME"/.config/sway
     fi
 }
-#
-# Setup
-#
 
-rm -f output.log
-touch output.log
-
-if [[ ! -f .state ]]; then
-    print ".state file not found. Creating it ..."
-    touch .state
-fi
-
-# Sourcing state updates all state variables for parts that
-# are already installed.
-# You can delete individual lines from .state to reinstall.
-brew_installed=""
-zsh_installed=""
-source .state
-
-if [[ "$OSTYPE" == "darwin"* ]]; then
-    if [[ ! "$brew_installed" = "true" ]]; then
-        install_brew
+setup() {
+    rm -f output.log
+    touch output.log
+    
+    if [[ ! -f .state ]]; then
+        print ".state file not found. Creating it ..."
+        touch .state
     fi
-    # Forcing brew to be in path
-    PATH="/usr/local/bin:$PATH"
-else
-    # Assuming Linux
-    if [[ -z "$linux_distro" ]]; then
-        read -p "Which distro are you on? (fedora/ubuntu) " -r linux_distro
-        if [[ "$linux_distro" = "fedora" ]] || [[ "$linux_distro" = "ubuntu" ]]; then
-            printf 'linux_distro="%s"\n' "$linux_distro" >> .state
-        else
-            print "Unknown distro. Exiting ..."
-            exit 1
+    
+    # Sourcing state updates all state variables for parts that
+    # are already installed.
+    # You can delete individual lines from .state to reinstall.
+    brew_installed=""
+    zsh_installed=""
+    source .state
+    
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+        if [[ ! "$brew_installed" = "true" ]]; then
+            install_brew
+        fi
+        # Forcing brew to be in path
+        PATH="/usr/local/bin:$PATH"
+    else
+        # Assuming Linux
+        if [[ -z "$linux_distro" ]]; then
+            read -p "Which distro are you on? (fedora/ubuntu) " -r linux_distro
+            if [[ "$linux_distro" = "fedora" ]] || [[ "$linux_distro" = "ubuntu" ]]; then
+                printf 'linux_distro="%s"\n' "$linux_distro" >> .state
+            else
+                print "Unknown distro. Exiting ..."
+                exit 1
+            fi
+        fi
+    
+        if [[ -z "$linux_is_desktop" ]]; then
+            read -p "Are you on a desktop? (y/N) " -n 1 -r linux_is_desktop
+            if [[ "$linux_is_desktop" =~ ^[yY]$ ]]; then
+                linux_is_desktop="true"
+            else
+                linux_is_desktop="false"
+            fi
+            printf 'linux_is_desktop="%s"\n' "$linux_is_desktop" >> .state
         fi
     fi
+}
 
-    if [[ -z "$linux_is_desktop" ]]; then
-        read -p "Are you on a desktop? (y/N) " -n 1 -r linux_is_desktop
-        if [[ "$linux_is_desktop" =~ ^[yY]$ ]]; then
-            linux_is_desktop="true"
-        else
-            linux_is_desktop="false"
+# Also symlinks configs:
+installs() {
+    if [[ "$linux_distro" = "fedora" ]]; then
+        if [[ ! "$kakcopradded" = "ture" ]]; then
+            print "Adding kak-lsp copr to fedora ..."
+            redirect_output "sudo dnf copr enable atim/kakoune -y"
+            echo 'kakcopradded="true"' >> .state
         fi
-        printf 'linux_is_desktop="%s"\n' "$linux_is_desktop" >> .state
-    fi
-fi
-
-#
-# Execution
-#
-
-if [[ "$linux_distro" = "fedora" ]]; then
-    if [[ ! "$kakcopradded" = "ture" ]]; then
-        print "Adding kak-lsp copr to fedora ..."
-        redirect_output "sudo dnf copr enable atim/kakoune -y"
-        echo 'kakcopradded="true"' >> .state
-    fi
-    if [[ ! "$yarnrepoadded" = "ture" ]]; then
-        print "Adding yarn repo to fedora ..."
-        redirect_output "curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo"
-        echo 'yarnrepoadded="true"' >> .state
-    fi
-fi
-
-if [[ ! "$zsh_installed" = "true" ]]; then
-    install_zsh
-fi
-
-for package in "${common_packages[@]}"; do
-    var_reference="${package}_installed"
-    if [[ ! "${!var_reference}" = "true" ]]; then
-        install "$package"
-    fi
-done
-
-if [[ "$linux_distro" = "fedora" ]]; then
-    print "Installing fedora packages ..."
-    for package in "${fedora_packages[@]}"; do
-        var_reference="${package//-/_}_installed"
-        if [[ ! "${!var_reference}" = "true" ]]; then
-            install "$package"
+        if [[ ! "$yarnrepoadded" = "ture" ]]; then
+            print "Adding yarn repo to fedora ..."
+            redirect_output "curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo"
+            echo 'yarnrepoadded="true"' >> .state
         fi
-    done
-fi
-
-if [[ "$linux_distro" = "ubuntu" ]]; then
-    print "Installing ubuntu packages ..."
-    for package in "${ubuntu_packages[@]}"; do
+    fi
+    
+    if [[ ! "$zsh_installed" = "true" ]]; then
+        install_zsh
+    fi
+    
+    for package in "${common_packages[@]}"; do
         var_reference="${package}_installed"
         if [[ ! "${!var_reference}" = "true" ]]; then
             install "$package"
         fi
     done
-fi
-
-if [[ "$OSTYPE" == "darwin"* ]]; then
-    for package in "${brew_packages[@]}"; do
-        var_reference="${package}_installed"
-        if [[ ! "${!var_reference}" = "true" ]]; then
-            install "$package"
-        fi
-    done
-
-    for package in "${brew_desktop_packages[@]}"; do
-        var_reference="${package}_installed"
-        if [[ ! "${!var_reference}" = "true" ]]; then
-            redirect_output "brew cask install $1"
-        fi
-    done
-else
-    # Assuming Linux
-    if [[ ! "$starship_installed" = "true" ]]; then
-        # Starship on Linux is only available as download
-        print "Installing starship ..."
-        curl -fsSL https://starship.rs/install.sh | sudo bash
-        echo "starship_installed=\"true\"" >> .state
+    
+    if [[ "$linux_distro" = "fedora" ]]; then
+        print "Installing fedora packages ..."
+        for package in "${fedora_packages[@]}"; do
+            var_reference="${package//-/_}_installed"
+            if [[ ! "${!var_reference}" = "true" ]]; then
+                install "$package"
+            fi
+        done
     fi
-
-    if [[ "$linux_is_desktop" = "true" ]]; then
-        print "Installing desktop packages ..."
-        for package in "${linux_desktop_packages[@]}"; do
+    
+    if [[ "$linux_distro" = "ubuntu" ]]; then
+        print "Installing ubuntu packages ..."
+        for package in "${ubuntu_packages[@]}"; do
             var_reference="${package}_installed"
             if [[ ! "${!var_reference}" = "true" ]]; then
                 install "$package"
             fi
         done
     fi
-fi
-
-if [[ ! "$ohmyzsh_installed" = "true" ]]; then
-    install_ohmyzsh
-    echo 'ohmyzsh_installed="true"' >> .state
-fi
-
-symlink_configs
-
-if [[ ! "$zshnvm_installed" = "true" ]]; then
-    print "Installing zsh_nvm ..."
-    mkdir -p "$HOME"/.oh-my-zsh/custom/plugins/
-    git clone https://github.com/lukechilds/zsh-nvm ~/.oh-my-zsh/custom/plugins/zsh-nvm 1>>output.log 2>&1 || error "Could not install zshnvm"
-    echo 'zshnvm_installed="true"' >> .state
-fi
-
-if [[ ! "$sourced" = "true" ]]; then
-    print "You must manually 'source ~/.zshrc'."
-    print "Then, run ./installer again."
-    echo 'sourced="true"' >> .state
-    exit 0
-fi
-
-if [[ ! "$node_installed" = "true" ]]; then
-    print "You must manually 'nvm install stable'."
-    print "Then, run ./installer again."
-    echo 'node_installed="true"' >> .state
-    exit 0
-fi
-
-if [[ ! "$npmpackages_installed" = "true" ]]; then
-    print "Installing npm packages ..."
-    redirect_output "npm install -g typescript"
-    redirect_output "npm install -g typescript-language-server"
-    redirect_output "npm install -g eslint-formatter-kakoune"
-    echo 'npmpackages_installed="true"' >> .state
-fi
-
-if [[ ! "$neovimdependencies_installed" = "true" ]]; then
-    print "Installing (Neo)Vim dependencies ..."
-    redirect_output "pip3 install --user --upgrade pynvim"
     
-    # vim-plug to manage plugins in vim
-    curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
-        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
-    # same for neovim
-    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
-        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
-    echo 'neovimdependencies_installed="true"' >> .state
-fi
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+        for package in "${brew_packages[@]}"; do
+            var_reference="${package}_installed"
+            if [[ ! "${!var_reference}" = "true" ]]; then
+                install "$package"
+            fi
+        done
+    
+        for package in "${brew_desktop_packages[@]}"; do
+            var_reference="${package}_installed"
+            if [[ ! "${!var_reference}" = "true" ]]; then
+                redirect_output "brew cask install $1"
+            fi
+        done
+    else
+        # Assuming Linux
+        if [[ ! "$starship_installed" = "true" ]]; then
+            # Starship on Linux is only available as download
+            print "Installing starship ..."
+            curl -fsSL https://starship.rs/install.sh | sudo bash
+            echo "starship_installed=\"true\"" >> .state
+        fi
+    
+        if [[ "$linux_is_desktop" = "true" ]]; then
+            print "Installing desktop packages ..."
+            for package in "${linux_desktop_packages[@]}"; do
+                var_reference="${package}_installed"
+                if [[ ! "${!var_reference}" = "true" ]]; then
+                    install "$package"
+                fi
+            done
+        fi
+    fi
+    
+    if [[ ! "$ohmyzsh_installed" = "true" ]]; then
+        install_ohmyzsh
+        echo 'ohmyzsh_installed="true"' >> .state
+    fi
+    
+    if [[ ! "$zshnvm_installed" = "true" ]]; then
+        print "Installing zsh_nvm ..."
+        mkdir -p "$HOME"/.oh-my-zsh/custom/plugins/
+        git clone https://github.com/lukechilds/zsh-nvm ~/.oh-my-zsh/custom/plugins/zsh-nvm 1>>output.log 2>&1 || error "Could not install zshnvm"
+        echo 'zshnvm_installed="true"' >> .state
+    fi
+    
+    symlink_configs
+    
+    if [[ ! "$sourced" = "true" ]]; then
+        print "You must manually 'source ~/.zshrc'."
+        print "Then, run ./installer again."
+        echo 'sourced="true"' >> .state
+        exit 0
+    fi
+    
+    if [[ ! "$node_installed" = "true" ]]; then
+        print "You must manually 'nvm install stable'."
+        print "Then, run ./installer again."
+        echo 'node_installed="true"' >> .state
+        exit 0
+    fi
+    
+    if [[ ! "$npmpackages_installed" = "true" ]]; then
+        print "Installing npm packages ..."
+        redirect_output "npm install -g typescript"
+        redirect_output "npm install -g typescript-language-server"
+        redirect_output "npm install -g eslint-formatter-kakoune"
+        echo 'npmpackages_installed="true"' >> .state
+    fi
+    
+    if [[ ! "$neovimdependencies_installed" = "true" ]]; then
+        print "Installing (Neo)Vim dependencies ..."
+        redirect_output "pip3 install --user --upgrade pynvim"
+        
+        # vim-plug to manage plugins in vim
+        curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
+            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+        # same for neovim
+        curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
+            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+        echo 'neovimdependencies_installed="true"' >> .state
+    fi
+    
+    if [[ ! "$kakpluginmanager_installed" = "true" ]]; then
+        print "Installing kakoune plugin manager ..."
+        mkdir -p "$HOME"/.config/kak/plugins
+        git clone https://github.com/andreyorst/plug.kak.git "$HOME"/.config/kak/plugins/plug.kak
+        echo 'kakpluginmanager_installed="true"' >> .state
+    fi
+    
+    if [[ ! "$tmuxpluginmanager_installed" = "true" ]]; then
+        print "Installing tmux plugin manager ..."
+        mkdir -p "$HOME"/.config/tmux/plugins
+        git clone https://github.com/tmux-plugins/tpm "$HOME"/.config/tmux/plugins/tpm
+        echo 'tmuxpluginmanager_installed="true"' >> .state
+    fi
+    
+    if [[ "$linux_distro" = "ubuntu" ]]; then
+        print "Remember to manually install kak-lsp as per the following link:"
+        print "https://github.com/ul/kak-lsp#others"
+    fi
+}
 
-if [[ ! "$kakpluginmanager_installed" = "true" ]]; then
-    print "Installing kakoune plugin manager ..."
-    mkdir -p "$HOME"/.config/kak/plugins
-    git clone https://github.com/andreyorst/plug.kak.git "$HOME"/.config/kak/plugins/plug.kak
-    echo 'kakpluginmanager_installed="true"' >> .state
-fi
-
-if [[ ! "$tmuxpluginmanager_installed" = "true" ]]; then
-    print "Installing tmux plugin manager ..."
-    mkdir -p "$HOME"/.config/tmux/plugins
-    git clone https://github.com/tmux-plugins/tpm "$HOME"/.config/tmux/plugins/tpm
-    echo 'tmuxpluginmanager_installed="true"' >> .state
-fi
-
-if [[ "$linux_distro" = "ubuntu" ]]; then
-    print "Remember to manually install kak-lsp as per the following link:"
-    print "https://github.com/ul/kak-lsp#others"
-fi
-
-cat <<EOF
-
+everything() {
+    setup
+    installs
+        
+    cat <<EOF
+        
 To finsh setup:
  * Install a patched font from https://github.com/ryanoasis/nerd-fonts
    and set it in your terminal emulator
@@ -378,5 +389,16 @@ To finsh setup:
  * Run ':PlugInstall' in NeoVim
  * Add .~/.gitconfigemail and set your email address
  * Don't forget to map capslock to <Ctrl>
-
+        
 EOF
+}
+
+case $1 in
+    "symlinks")
+        symlink_configs
+        ;;
+    *)
+        everything
+        ;;
+esac
+
